title: Chapter

columns:
  main:
    width: 2/3
    sections:
      fields:
        type: fields
        fields:
          subtitle: 
            label: Subtitle
            type: text
          text: 
            label: Content
            type: blocks
            fieldsets:
              - heading
              - text
              bigtext:
                name: Big text
                icon: text
                wysiwyg: true
                preview: text
                fields: 
                  text:
                    label: Text
                    type: writer
                    nodes: false
                    placeholder: field.blocks.text.placeholder
              - list
              - gallery
              - image

  sidebar:
    width: 1/3
    sections:
      files:
        label: Images
        type: files

